language: node_js
node_js:
 - "node"

script:
 - npm test
 - npm run build

after_success:
 - cd dist && find . -type f -exec curl -u $FTP_U:$FTP_P --ftp-create-dirs -T {} ftp://toaster-online.de/{} \;

#notifications:
 # email:
  #  recipients:
   #   - $NOTIFICATION_MAIL
    #on_success: always # default: change
    #on_failure: always # default: always
